
// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://qgzompfkqrfgjnbxwhip.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InFnem9tcGZrcXJmZ2puYnh3aGlwIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDc0NzIwMzEsImV4cCI6MjA2MzA0ODAzMX0.5nN4G3tNcf4QOJQ989B-I6gHPlll9y3nCWicDKbeZlI";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    autoRefreshToken: true,
    persistSession: true,
    detectSessionInUrl: false,
    storage: localStorage,
  },
  realtime: {
    params: {
      eventsPerSecond: 10
    }
  },
  global: {
    headers: {
      'x-application-name': 'cash-my-points'
    }
  },
  db: {
    schema: 'public'
  }
});

// Enhanced error handling functions for Supabase operations
export const safeSupabaseOperation = async <T>(
  operation: () => Promise<{ data: T | null; error: any }>,
  errorMessage: string = "Database operation failed"
): Promise<T> => {
  try {
    const { data, error } = await operation();
    
    if (error) {
      console.error(`Supabase error:`, error);
      
      // Check for the infinite recursion error and provide a more helpful message
      if (error.code === '42P17' && error.message.includes('infinite recursion')) {
        throw new Error(`${errorMessage}: There's a problem with the database security policies. Please contact the administrator.`);
      }
      
      throw new Error(`${errorMessage}: ${error.message}`);
    }
    
    return data as T;
  } catch (error) {
    console.error(`Error during operation:`, error);
    throw error;
  }
};

// Direct admin operations that bypass RLS using security definer functions
export const directAdminOperation = async <T>(
  operation: "is_user_admin" | "is_admin",  // Update this to include all valid operation names
  params?: Record<string, any>
): Promise<T> => {
  try {
    const { data, error } = await supabase.rpc(operation, params);
    
    if (error) {
      console.error(`Supabase RPC error for ${operation}:`, error);
      throw new Error(`Operation failed: ${error.message}`);
    }
    
    return data as T;
  } catch (error) {
    console.error(`Error during admin operation:`, error);
    throw error;
  }
};
